pub fn decrypt_url(encrypted: &str) -> String {
    let mut decrypted = String::with_capacity(encrypted.len() / 2);

    let bytes = encrypted.as_bytes();

    // We iterate over the string in chunks of 2
    for chunk in bytes.chunks(2) {
        if chunk.len() < 2 {
            break;
        }

        let decoded_char_str = match chunk {
            b"79" => "A",
            b"7a" => "B",
            b"7b" => "C",
            b"7c" => "D",
            b"7d" => "E",
            b"7e" => "F",
            b"7f" => "G",
            b"70" => "H",
            b"71" => "I",
            b"72" => "J",
            b"73" => "K",
            b"74" => "L",
            b"75" => "M",
            b"76" => "N",
            b"77" => "O",
            b"68" => "P",
            b"69" => "Q",
            b"6a" => "R",
            b"6b" => "S",
            b"6c" => "T",
            b"6d" => "U",
            b"6e" => "V",
            b"6f" => "W",
            b"60" => "X",
            b"61" => "Y",
            b"62" => "Z",
            b"59" => "a",
            b"5a" => "b",
            b"5b" => "c",
            b"5c" => "d",
            b"5d" => "e",
            b"5e" => "f",
            b"5f" => "g",
            b"50" => "h",
            b"51" => "i",
            b"52" => "j",
            b"53" => "k",
            b"54" => "l",
            b"55" => "m",
            b"56" => "n",
            b"57" => "o",
            b"48" => "p",
            b"49" => "q",
            b"4a" => "r",
            b"4b" => "s",
            b"4c" => "t",
            b"4d" => "u",
            b"4e" => "v",
            b"4f" => "w",
            b"40" => "x",
            b"41" => "y",
            b"42" => "z",
            b"08" => "0",
            b"09" => "1",
            b"0a" => "2",
            b"0b" => "3",
            b"0c" => "4",
            b"0d" => "5",
            b"0e" => "6",
            b"0f" => "7",
            b"00" => "8",
            b"01" => "9",
            b"15" => "-",
            b"16" => ".",
            b"67" => "_",
            b"46" => "~",
            b"02" => ":",
            b"17" => "/",
            b"07" => "?",
            b"1b" => "#",
            b"63" => "[",
            b"65" => "]",
            b"78" => "@",
            b"19" => "!",
            b"1c" => "$",
            b"1e" => "&",
            b"10" => "(",
            b"11" => ")",
            b"12" => "*",
            b"13" => "+",
            b"14" => ",",
            b"03" => ";",
            b"05" => "=",
            b"1d" => "%",
            _ => "",
        };

        decrypted.push_str(decoded_char_str);
    }

    decrypted
}
